########################################
##      Tax Computation System        ##
########################################
# Docker system composition descriptor #
########################################
# Author: Sebastien Mosser             #
# Version: 1.0                         #
########################################

## Start the system with "docker-compose up -d"
## Shutdown it with "docker-compose down"
## To clean your docker install: "docker system prune"
## To purge your docker install: "docker system prune -a"

version: '3'

services:

  database:                       # MongoDB database
    container_name: tcs_mongo
    image: mongo:3.0
    volumes:
      - "./mongo_data:/data/db"
    ports:
      - "27017:27017"

  rpc:                            # Tax Computation, on port 9090
    container_name: tcs_rpc
    image: petitroll/tcs-rpc
    ports:
      - "9090:8080"

  resources:                      # ID generators, on port 9070
    container_name: tcs_rest
    image: petitroll/tcs-rest
    ports:
      - "9070:8080"


  cadvisor:                       # Container monitoring, on port 8090
    container_name: tcs_monitoring
    image: google/cadvisor
    ports:
      - "8090:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
