version: '3'

services:

  bus:
    image: hcsoa/bus
    build: ../integration
    volumes:
      - ./data/deploy:/servicemix/deploy # DEBUG
      - ./data/input:/servicemix/camel/input
      - ./data/output:/servicemix/camel/output
      - ./data/input/email:/servicemix/camel/input/email
    ports:
      - "8181:8181"
    links:
      - car:hcs-car
      - car-ext:g2-car
      - flight:hcs-flight
      - flight-ext:g1-flight
      - hotel:hcs-hotel
      - hotel-ext:g7-hotel
      - database:db
      - ftp-server
      - approver

  approver:
    image: hcsoa/approver
    build: ../services/approver
    ports:
      - "9090:8080"
    links:
      - database

  car:
    image: hcsoa/car
    build: ../services/car
    environment:
      - db_host=database
      - db_port=27017
    depends_on:
      - database
    links:
      - database
    ports:
      - "9091:8080"

  flight:
    image: hcsoa/flight
    build: ../services/flight
    environment:
      - db_host=database
      - db_port=27017
    depends_on:
      - database
    links:
      - database
    ports:
      - "9092:8080"

  hotel:
    image: hcsoa/hotel
    build: ../services/hotel
    environment:
      - db_host=database
      - db_port=27017
    depends_on:
      - database
    links:
      - database
    ports:
      - "9093:8080"

  mail:
    image: hcsoa/mail
    build: ../services/mail
    ports:
      - "9094:8080"

  car-ext:
    image: hcsoa/car-ext
    ports:
      - "9095:8080"

  hotel-ext:
    image: hcsoa/hotel-ext
    ports:
      - "9096:8080"

  flight-ext:
    image: hcsoa/flight-ext
    ports:
      - "9097:8080"

  ftp-server:
    image: onekilo79/ftpd_test
    ports:
      - "11021:21"
      - "30000-30009:30000-30009"

  database:
    image: mongo:3.4.9
    ports:
      - "27017:27017"
    volumes:
      - "./mongo_data:/data/db"
      - "./import:/import"
    ports:
      - "27017:27017"

  cadvisor:
    image: petitroll/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
