version: '3'

services:

  approver:
    image: hcsoa/approver
    build: ../services/approver
    ports:
      - "9090:8080"

  car:
    image: hcsoa/car
    build: ../services/car
    environment:
      - db_host=database
      - db_port=27017
    depends_on:
      - database
    links:
      - database
    ports:
      - "9091:8080"

  flight:
    image: hcsoa/flight
    build: ../services/flight
    environment:
      - db_host=database
      - db_port=27017
    depends_on:
      - database
    links:
      - database
    ports:
      - "9092:8080"

  hotel:
    image: hcsoa/hotel
    build: ../services/hotel
    environment:
      - db_host=database
      - db_port=27017
    depends_on:
      - database
    links:
      - database
    ports:
      - "9093:8080"

  mail:
    image: hcsoa/mail
    build: ../services/mail
    ports:
      - "9094:8080"

  database:
    image: mongo:3.4.9
    volumes:
      - "./mongo_data:/data/db"

  cadvisor:
    image: petitroll/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"